name: dgaddy
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - notebook
  - pytorch=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - libsndfile
  - absl-py
  - numpy=1.23
  - librosa=0.8.1
  - pysoundfile
  - matplotlib
  - scipy
  - numba
  - unidecode
  - pip
  - pip:
    - jiwer==2.2.1
    - deepspeech==0.9.3
    - praat-textgrids
    - noisereduce==1.1.0
