# Default configuration for Silent Speech EMG Interface

# Data Configuration
data:
  sampling_rate: 1000  # Hz
  window_size: 256    # samples
  hop_length: 128     # samples
  n_channels: 8       # number of EMG channels
  max_sequence_length: 512
  augmentation:
    noise_level: 0.1
    time_stretch_range: [0.9, 1.1]
    
# Model Configuration
model:
  type: "transformer"
  encoder:
    n_layers: 6
    n_heads: 8
    d_model: 512
    d_ff: 2048
    dropout: 0.1
  decoder:
    n_layers: 6
    n_heads: 8
    d_model: 512
    d_ff: 2048
    dropout: 0.1
  embedding:
    vocab_size: 32000
    max_position_embeddings: 512
    
# Training Configuration
training:
  batch_size: 32
  learning_rate: 0.0001
  warmup_steps: 4000
  max_epochs: 100
  early_stopping:
    patience: 10
    min_delta: 0.001
  optimizer:
    type: "adam"
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.01
  label_smoothing: 0.1
  gradient_clip_val: 1.0
  
# Cross Validation
cross_validation:
  n_folds: 3
  shuffle: true
  seed: 42
  
# Evaluation
evaluation:
  metrics:
    - "wer"
    - "cer"
    - "perplexity"
  beam_size: 5
  length_penalty: 0.6
  
# Logging
logging:
  wandb:
    project: "silent-speech-interface"
    entity: "anthony-l-sanchez-ie-university"
  log_every_n_steps: 100
  save_every_n_epochs: 1
  
# Hardware
hardware:
  precision: 16  # mixed precision training
  accelerator: "auto"  # auto-detect GPU/CPU
  devices: 1
  
# Demo Interface
demo:
  port: 7860
  share: false  # set to true to create public URL
  theme: "default"
  max_batch_size: 1
  update_interval: 100  # ms 