_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
